version: '3.8'

services:
  redis:
    image: redis:7.4.2
    container_name: redis
    restart: always
    environment:
      - REDIS_HOSTS=local:redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - "6379:6379"
    networks:
      - app-network

  # 🔹 Redis Commander (Web UI)
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8082:8081"
    networks:
      - app-network

  # 🔹 PostgreSQL Database
  postgres_db:
    image: postgres:17.2
    container_name: postgres_db
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=messenger_app
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # 🔹 PG Admin (Web UI)
  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

